---
# tasks file for ansible-system-hardening
- name: install package needed 
  package: name={{ item }} state=present update_cache=yes
  with_items:
     - yum-plugin-security
     - yum-utils
     - fail2ban
     - lynis
     - arpwatch

#- name: Check and install security updates
#  template: src= dest=
# yum updateinfo summary
# yum --security check-update
# yum –y --security update
     
- name: copy over ssh-banner
  template: src=templates/ssh-banner dest=/etc/ssh/ssh-banner

- name: copy over sshd_config
  template: src=templates/sshd_config dest=/etc/ssh/sshd_config 
  notify: restart sshd

- name: Copy over systctl.conf
  template: src=templates/sysctl.conf dest=/etc/sysctl.conf

- name: copy over fail2ban jail.conf
  template: src=templates/jail.conf dest=/etc/fail2ban/jail.conf

- name: add fail2ban rules in jail.local
  template: src=templates/jail.local dest=/etc/fail2ban/jail.local
  notify: start fail2ban
  
- name: create rules for IPtables
  template: src=templates/iptables_rules.sh dest=/opt/iptables_rules.sh mode="u+rwx"
  notify: start iptables
  
- name: running iptable_rules.sh
#  command: ./iptables_rules.sh chdir=/opt/
  command: sh /opt/iptables_rules.sh
  notify: restart iptables

