---
# tasks file for ansible-ssh-keygen

- name: Generate public sshkeys
  user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
#  creates: .ssh/id_rsa
#  command: ssh-keygen -N '' {{ ansible_env.HOME }}/.ssh/id_rsa

#- name: enable ssh-agent
#  shell: echo "ssh-agent = $(ssh-agent)"

- name: Setting up ssh-agent
  shell: eval $(ssh-agent) && ssh-add

#- name: add ssh-key to ssh-agent
#  shell: ssh-add

- name: Add ssh key to target host
  command: cat "{{ ansible_env.HOME }}"/.ssh/id_rsa.pub
  register: ssh_keys
  tags: ssh_gen

- name: check keys
  debug: msg="{{ ssh_keys.stdout }}"
  tags: ssh_gen

- name: deploy keys on all servers
  authorized_key: user=root key="{{ item[0] }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
     - ssh_keys.stdout
     - ["{{ groups['docker2'] }}","{{ groups['docker'] }}"]
  tags: ssh_gen
