---
# tasks file for ansible-rhelphp5
- name: add latest epel release
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: add webtatic release
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

- name: install PHP 5.5 mod_php SAPI
  package: name={{ item }} state=present update_cache=yes
  with_items:
      - php55w
      - php55w-opcache
      - php55w-odbc
  when: php_version == "php5"

- name: install PHP 7
  package: name={{ item }} state=present update_cache=yes
  with_items:
    - php70w
    - php70w-opcache
    - php70w-odbc
  when: php_version == "php7"

- name: install httpd
  package: name=httpd state=present update_cache=yes
  notify: start httpd

- name : copy over index.php
  template: src=templates/index.php dest=/var/www/html/index.php
  notify: restart httpd

- name: Copy over php.ini
  template: src=templates/php.ini dest=/etc/php.ini

- name: Copy over odbc.ini 
  template: src=templates/odbc.j2 dest=/etc/odbc.ini

- name: Install goss
  shell: 'curl -fsSL https://goss.rocks/install | sh'
  args:
    creates: "/usr/local/bin/goss"

- name: Place goss file
#  template: src=templates/goss.json dest=/goss.json
  template: src=templates/goss.yaml dest=./goss.yaml

- name: validate goss
  command: 'goss --gossfile "./goss.yaml" validate --format documentation'

