---
# tasks file for ansible-informixclient-csdk
- name: Create folder /opt/installer
  file: path=/opt/installer/clientsdk.4.10.FC7DE.LINUX state=directory mode=0644

- name: Copy files to remote host
  template: src=templates/informixcsdk.ini dest=/opt/installer/informixcsdk.ini mode=0644

- name: Unarchive downloaded installer
  unarchive: src=files/clientsdk.4.10.FC7DE.LINUX.tar dest=/opt/installer/clientsdk.4.10.FC7DE.LINUX creates=opt/installer/clientsdk.4.10.FC7DE.LINUX creates=/opt/installer/installclientsdk

- name: Run installClientsdk
  shell: "./installclientsdk -i silent -DLICENSE_ACCEPTED=TRUE -f /opt/installer/informixcsdk.ini"
  args:  
      chdir: /opt/installer/clientsdk.4.10.FC7DE.LINUX 
      creates: /opt/IBM/informix/csdk/uninstall
#      warn: false
# install glibc

#- name: sym link libexpat.so.1 to libexpat.so.0
#  file: src={{ item.0 }} dest={{ item.1 }} state=link force=yes
#  with_items:
#     - [ /lib64/libexpat.so.1, /lib64/libexpat.so.0]
#     - [ /usr/lib64/libssl.so.1.0.1e , /usr/lib64/libssl.so.6 ]
#     - [ /usr/lib64/libcrypto.so.1.0.1e, /usr/lib64/libcrypto.so.6 ]

- name: sym link libexpat.so.1 to libexpat.so.0
  file: src=/lib64/libexpat.so.1 dest=/lib64/libexpat.so.0 state=link force=yes


- name: sym link libssl.so.1.0.0 to libssl.so.6
  file: src=/usr/lib64/libssl.so.1.0.1e dest=/usr/lib64/libssl.so.6 state=link force=yes


- name: sym link libcrypto.so.1.0.0 to libcrypto.so.6
  file: src=/usr/lib64/libcrypto.so.1.0.1e dest=/usr/lib64/libcrypto.so.6 state=link force=yes


- name : Install libpng
  package: name={{ item }} state=present update_cache=yes
  with_items:
      - libpng
      - php-devel
  
- name: Start OTP server
  command: ./StartApache
  args:
    chdir: /opt/IBM/informix/csdk/OAT 
#      creates: /opt/IBM/informix/csdk/

- name: extract pdo_informix
  unarchive: src="https://pecl.php.net/get/{{ pdo_informix }}.tgz" dest=/opt/ remote_src=yes copy=no

#- name: change dir to pdo_informix
#  shell: chdir=/opt/{{ pdo_informix }} ls
  
- name: run phpize
  command: "{{ item }} chdir=/opt/{{ pdo_informix }}"
  with_items:
    - phpize
    - ./configure --with-pdo-informix=/opt/IBM/informix
  args:
   chdir: /opt/{{ pdo_informix }} ls

- name: run make
  make: target= {{ item }} chdir=/opt/{{ pdo_informix }
  with_items:
    - make
    - make install

#- name: run ./configure
#  command: ./configure --with-pdo-informix=/opt/IBM/informix

#- name: run make
#  command: make

#- name:  run make install
#  command: make install
