---
# tasks file for ansible-nginx-hardening
#- name: Update system 
#  package: name=* state=latest update_cache=yes

- name: Create /etc/nginx/ssl
  file: path=/etc/nginx/ssl state=directory mode=0644

- name: generate cert
  command: 'openssl req -new -x509 -nodes -sha256 -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/C=MY/ST=Selangor/L=PetalingJaya/O=Censof/OU=Devops/CN=test123.com" '
#  creates: /etc/nginx/ssl/nginx.crt
  

- name: generate dhparam
  command: "openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096"

- name: copy over ssl.conf
  template: src=templates/ssl.conf dest=/etc/nginx/conf.d/ssl.conf

- name: copy over ssl.conf
  template: src=templates/ssl.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

#- name : restart nginx
#  command: service nginx restart

